config/routes.rb
Rails.application.routes.draw do
  root :to =>"homes#top"
  get "/about" => "homes#about"

  get "/tag" => "homes#index"

  #タグによって絞り込んだ投稿を表示するアクションへのルーティング
  resources :tags do
    get 'likes', to: 'likes#search'
  end

  # 検索
  get "search" => "searches#search"
  get "search_tag" => "searches#search_tag"

  #顧客用
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  #管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    resources :customers, only: [:index, :show, :update, :edit] do
      resource :relationships, only: [:create, :destroy]
      get 'index' => 'relationships#index', as: 'index'
      member do
        get :edit_password
        get :unsubscribe # 退会確認画面
        patch :withdrawal # 論理削除用のルーティング
        get :favorites
      end
    end

    resources :likes do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :likes, only:[:index, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :likes ,dependent: :destroy
  has_many :comments
  has_many :favorites,dependent: :destroy

  # バリデーション
  validates :name, presence: true, length: { maximum: 20 }

  # タグ関連
  has_many :like_tags, dependent: :destroy
  has_many :tags, through: :like_tags

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローしたときの処理
  def follow(customer_id)
    relationships.create(followed_id: customer_id)
  end
  # フォローを外すときの処理
  def unfollow(customer_id)
    relationships.find_by(followed_id: customer_id).destroy
  end
  # フォローしているか判定
  def following?(customer)
    followings.include?(customer)
  end

  # 検索方法
  def self.looks(word)
    @customer = Customer.where("name LIKE?","%#{word}%")
  end

  has_one_attached :image

  def get_profile_image
    (image.attached?) ? image : 'no_image.jpg'
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all.page(params[:page]).per(15)
  end

  def show
    @customer = Customer.find(params[:id])
    @likes = @customer.likes
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
     customer = Customer.find(params[:id])
     customer.update(customer_params)
     redirect_to admin_customer_path(customer)
  end

  private
  def customer_params
    params.require(:customer).permit(:is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container mt-5 mb-5">

  <div class="center-block">
    <h2 class="text-primary mb-4 font-weight-bold">退会ステータス</h2>
  </div>

  <%= form_with(model: @customer, url: admin_customer_path, method: :patch) do |f| %>
    <%#= render "public/shared/error_messages", resource: resource %>

    <!--退会ステータス-->
    <div class="pb-4">
      <%= f.label :"会員ステータス", class: "col-sm-4 control-label" %>
    　<%= f.radio_button :is_deleted, true %>
    　<%= f.label :is_deleted, "退会", {value: :true, style: "display: inline-block;"} %>
    　<%= f.radio_button :is_deleted, false %>
    　<%= f.label :is_deleted, "有効", {value: :false, style: "display: inline-block;"} %>
    </div>

    <div class="actions  col-9 col-offset-4">
      <%= f.submit '変更を保存する' ,class: "btn btn-success" %>
    </div>

  </div>
  <% end %>

</div>

app/views/admin/customers/index.html.erb
<div class="container">

  <div class="border-right border-left border-bottom p-2 px-4">
    <h4>会員一覧情報</h4>
  </div>

  <!-- ユーザーの詳細 -->
  <div class="border-right border-left border-bottom">

    <!--プロフィール画像、名前、プロフィール文-->
    <div class="border-bottom p-2">

      <div class="row">
        <div class="col-1 mx-3 font-weight-bold"></div>
        <div class="col-7 font-weight-bold">名前</div>
        <div class="col-3 font-weight-bold">退会ステータス</div>
      </div>

    </div>

    <% @customers.each do |customer| %>
    <div class="border-bottom p-2">
      <div class="row">
        <span class="col-1 mx-3">
          <%= link_to admin_customer_path(customer.id) do %>
          <%= image_tag customer.get_profile_image, size: '40x40',class:"border" %>
          <% end %>
        </span>
        <h4 class="col-7">
          <%= link_to admin_customer_path(customer.id), :style=>"text-decoration: none; color: #000;" do %>
          <%= customer.name %>
          <% end %>
        </h4>
        <div class="col-3">
          <% if customer.is_deleted %>
            <span class="text-secondary font-weight-bold">退会</span>
          <% else %>
            <span class="text-success font-weight-bold">有効</span>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>

     <%= paginate @customers %>

  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">

  <div class="border-right border-left border-bottom p-2 px-4">
    <h4 class="text-primary font-weight-bold">プロフィール</h4>
  </div>

  <!-- ユーザーの詳細 -->
  <div class="border-right border-left border-bottom p-4">
    <div class="row">

      <!--プロフィール画像、名前、プロフィール文-->
      <div class="col-md-7 p-4">
        <%= image_tag @customer.get_profile_image, size: '100x100',class:"border" %>
        <h3><%= @customer.name %></h3>
        <p><%= @customer.profile %></p>
      </div>

      <!--退会ステータス編集ボタン-->
      <div class="col-md-5 p-4">
        <div class="row">
        <% if @customer.is_deleted %>
          退会ステータス：
          <h2 class="text-secondary font-weight-bold">退会</h2>
        <% else %>
          退会ステータス：
          <h2 class="text-success font-weight-bold">有効</h2>
        <% end %>
        </div>

        <%= link_to "退会ステータス編集", edit_admin_customer_path(@customer.id), class:"btn btn-warning my-4" %>

      </div>

    </div>
  </div>

  <!-- ユーザーの投稿一覧 -->
  <% @likes.each do |l| %>
  <%= render 'public/likes/like', like: l %>
  <% end %>

</div>