config/routes.rb
Rails.application.routes.draw do
  root :to =>"homes#top"
  get "/about" => "homes#about"

  get "/tag" => "homes#index"

  #タグによって絞り込んだ投稿を表示するアクションへのルーティング
  resources :tags do
    get 'likes', to: 'likes#search'
  end

  # 検索
  get "search" => "searches#search"
  get "search_tag" => "searches#search_tag"

  #顧客用
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  #管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    resources :customers, only: [:index, :show, :update, :edit] do
      resource :relationships, only: [:create, :destroy]
      get 'index' => 'relationships#index', as: 'index'
      member do
        get :edit_password
        get :unsubscribe # 退会確認画面
        patch :withdrawal # 論理削除用のルーティング
        get :favorites
      end
    end

    resources :likes do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :likes, only:[:index, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_customer!

  def search
    @range = params[:range]
    @word = params[:word]

    if @range == "ユーザー検索"
      @customers = Customer.looks(params[:word])

    elsif @range == "キーワード検索"
      @likes = Like.looks(params[:word])

    elsif @range == "タグ検索"
      #検索結果画面でもタグ一覧表示
      @tag_list = Tag.all
      #検索されたタグを受け取る
      @tags = Tag.where(tag_name: params[:word])
      #検索されたタグに紐づく投稿を表示
      @likes = Like.all
    end

  end

  def search_tag

    #検索結果画面でもタグ一覧表示
    @tag_list = Tag.all
    #検索されたタグを受け取る
    @tag = Tag.find(params[:tag_id])
    #検索されたタグに紐づく投稿を表示
    @likes = @tag.likes.all
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<% if customer_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
    <div class="d-flex align-items-center">
      <div class="col-md-6"><%= f.text_field :word,class: "form-control" ,placeholder: "Search" %></div>
      <div class="col-md-4 text-right"><%= f.select :range, options_for_select([['ユーザー検索'], ['キーワード検索'],['タグ検索']]) %></div>
      <div class="col-md-2"><%= f.submit "検索", class: "btn btn-light" %></div>
    </div>
    <% end %>
  </div>
<% end %>

app/views/searches/search.html.erb
<div class="container">

  <div class="border-right border-left border-bottom p-2 px-4">

    <% if @range == "ユーザー検索" %>
    <h4 class="text-primary font-weight-bold">検索名：<%= @word %></h4>
    <% elsif @range == "キーワード検索" %>
    <h4 class="text-primary font-weight-bold">検索ワード：<%= @word %></h4>
    <% elsif @range == "タグ検索" %>
    <h4 class="text-primary font-weight-bold">検索タグ：<%= @word %></h4>
    <% end %>

  </div>

  <!-- ユーザーの詳細 -->
  <div class="border-right border-left border-bottom">

    <!--プロフィール画像、名前、プロフィール文-->
    <div class="border-bottom d-flex">

      <% if @range == "ユーザー検索" %>
      <div class="col-1 mx-3 font-weight-bold p-2"></div>
      <div class="col-3 font-weight-bold p-2">名前</div>
      <div class="col-7 font-weight-bold p-2">プロフィール</div>
      <% else %>
      <div class="col-10 font-weight-bold p-2">関連する投稿一覧</div>
      <% end %>

    </div>
  </div>

    <div>

      <% if @range == "ユーザー検索" %>

        <% @customers.each do |customer| %>

          <div class="border-right border-left border-bottom p-2">
            <div class="row">
              <span class="col-1 mx-3">
                <%= link_to customer_path(customer.id) do %>
                <%= image_tag customer.get_profile_image, size: '40x40',class:"border" %>
                <% end %>
              </span>
              <h4 class="col-3">
                <%= link_to customer_path(customer.id), :style=>"text-decoration: none; color: #000;" do %>
                <h4 class="font-weight-bold"><%= customer.name %></h4>
                <% end %>
              </h4>
              <div class="col-7">
                <p><%= customer.profile %></p>
              </div>
            </div>
          </div>

        <% end %>

      <% elsif @range == "キーワード検索" %>

        <!-- ユーザーの投稿一覧 -->

        <% @likes.each do |l| %>
        <div id="favorite_buttons_<%= l.id %>">
          <%= render 'public/likes/like', like: l %>
        </div>
        <% end %>


      <% elsif @range == "タグ検索" %>

        <!-- ユーザーの投稿一覧 -->
        <% @tags.each do |tag| %>

          <% tag.likes.each do |like| %>
            <div id="favorite_buttons_<%= like.id %>">
            <%= render 'public/likes/like', like: like %>
            </div>
          <% end %>

        <% end %>

      <% else %>
      <% end %>


    </div>

  </div>
</div>

app/views/searches/search_tag.html.erb
<div class="container">

  <div class="border-right border-left border-bottom p-2 px-4">
    <h4>タグが「
    <span class="text-primary font-weight-bold"><%= @tag.tag_name %></span>
    」の投稿一覧</h4>
  </div>

  <!-- ユーザーの詳細 -->
  <div class="border-right border-left border-bottom">

    <!--検索結果で出たユーザーの情報-->
    <% @likes.each do |l| %>
    <div id="favorite_buttons_<%= l.id %>">
    <%= render 'public/likes/like', like: l %>
    </div>
    <% end %>

  </div>
</div>