config/routes.rb
Rails.application.routes.draw do
  root :to =>"homes#top"
  get "/about" => "homes#about"

  get "/tag" => "homes#index"

  #タグによって絞り込んだ投稿を表示するアクションへのルーティング
  resources :tags do
    get 'likes', to: 'likes#search'
  end

  # 検索
  get "search" => "searches#search"
  get "search_tag" => "searches#search_tag"

  #顧客用
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  #管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    resources :customers, only: [:index, :show, :update, :edit] do
      resource :relationships, only: [:create, :destroy]
      get 'index' => 'relationships#index', as: 'index'
      member do
        get :edit_password
        get :unsubscribe # 退会確認画面
        patch :withdrawal # 論理削除用のルーティング
        get :favorites
      end
    end

    resources :likes do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :likes, only:[:index, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>おしゃべりるーむ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダー-->
    <header>
      <nav class="navbar navbar-dark p-3">
        <div class="d-flex col-md-2 mb-2 mb-lg-0 flex-wrap flex-md-nowrap justify-content-between">

          <!--タイトルロゴ-->
          <a class="navbar-brand" href="/">
            <%= image_tag 'logo.png', size: '100x100' %>
          </a>
        </div>

        <!--検索-->
        <div class="col-md-8">
          <%= render 'searches/search' %>
        </div>

        <div class="col-md-2 d-flex align-items-center justify-content-md-end mt-3 mt-md-0">

          <div class="dropdown">
            <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false">

              <!--adminログイン時のヘッダー-->
              <% if admin_signed_in? %>
              ログアウト
              <!--customerログイン時のヘッダー-->
              <% elsif customer_signed_in? %>
              プロフィール
              <!--ゲストログイン時のヘッダー-->
              <% else %>
              ログインはこちら
              <% end %>
            </button>

            <!--ユーザー関連の情報-->
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">

              <!--adminログイン時のヘッダー-->
              <% if admin_signed_in? %>

              <!--ログアウトする-->
              <li class="text-center">
                <a class="dropdown-item">
                  <%= link_to destroy_admin_session_path, method: :delete, :style=>"text-decoration: none; color: #000;" do %>ログアウト<% end %>
                </a>
              </li>

              <!--customerログイン時のヘッダー-->
              <% elsif customer_signed_in? %>

              <!--プロフィールに遷移-->
              <li class="text-center">
                <a class="dropdown-item">
                  <%= link_to  customer_path(current_customer), :style=>"text-decoration: none; color: #000;" do %>プロフィール<% end %>
                </a>
              </li>

              <!--メールアドレス編集に遷移-->
              <li class="text-center">
                <a class="dropdown-item">
                  <%= link_to  edit_password_customer_path(current_customer), :style=>"text-decoration: none; color: #000;" do %>パスワード<% end %>
                </a>
              </li>

              <!--ログアウトする-->
              <li class="text-center">
                <a class="dropdown-item">
                  <%= link_to destroy_customer_session_path, method: :delete, :style=>"text-decoration: none; color: #000;" do %>ログアウト<% end %>
                </a>
              </li>

              <!--退会する-->
              <li class="text-center">
                <a class="dropdown-item">
                  <%= link_to unsubscribe_customer_path(current_customer), :style=>"text-decoration: none; color: #F00;" do %>退会<% end %>
                </a>
              </li>

              <!--ゲストログイン時のヘッダー-->
              <% else %>

              <!--ログイン画面に遷移-->
              <li class="text-center">
                <a class="dropdown-item link-str">
                  <%= link_to  new_customer_session_path, :style=>"text-decoration: none; color: #000;" do%>ログイン<% end %>
                </a>
              </li>

              <!--新規登録画面に遷移-->
              <li class="text-center">
                <a class="dropdown-item">
                  <%= link_to new_customer_registration_path, data: {"turbolinks" => false}, :style=>"text-decoration: none; color: #000;" do %>新規登録<% end %>
                </a>
              </li>

              <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="container">
      <div class="row">

        <!--サイドバー-->
        <div class="border col-md-3 bg-light">
          <div class="position-sticky py-md-5">
            <ul class="nav flex-column">

              <!--adminログイン時のヘッダー-->
              <% if admin_signed_in? %>

              <!--ホーム画面に遷移-->
              <li class="nav-item">
                <a class="nav-link active" aria-current="page">
                  <%= link_to root_path, :style=>"text-decoration: none; color: #000;" do %>
                    <i class="fas fa-home fa-2x"></i><span class="mx-2">ホーム</span>
                  <% end %>
                </a>
              </li>

              <!--ユーザー一覧に遷移-->
              <li class="nav-item">
                <a class="nav-link active" aria-current="page">
                  <%= link_to admin_customers_path, :style=>"text-decoration: none; color: #000;" do %>
                    <i class="fas fa-user fa-2x"></i><span class="mx-2">会員一覧</span>
                  <% end %>
                </a>
              </li>

              <!--customerログイン時のヘッダー-->
              <% elsif customer_signed_in? %>

              <!--ホーム画面に遷移-->
              <li class="nav-item">
                <a class="nav-link active" aria-current="page">
                  <%= link_to root_path, :style=>"text-decoration: none; color: #000;" do %>
                    <i class="fas fa-home fa-2x"></i><span class="mx-2">ホーム</span>
                  <% end %>
                </a>
              </li>

              <!--ユーザー一覧情報のページに遷移-->
              <li class="nav-item">
                <a class="nav-link">
                  <%= link_to likes_path, :style=>"text-decoration: none; color: #000;" do %>
                    <i class="fas fa-laugh-squint fa-2x"></i><span class="mx-2">すべての投稿から探す</span>
                  <% end %>
                </a>
              </li>

              <!--タグ一覧情報のページに遷移-->
              <li class="nav-item">
                <a class="nav-link">
                  <%= link_to tag_path, :style=>"text-decoration: none; color: #000;" do %>
                    <i class="fas fa-tag fa-2x"></i><span class="mx-2">タグから探す</span>
                  <% end %>
                </a>
              </li>

              <!--いいねした投稿の一覧情報のページに遷移-->
              <li class="nav-item">
                <a class="nav-link">
                  <%= link_to favorites_customer_path(current_customer), :style=>"text-decoration: none; color: #000;" do %>
                    <i class="fas fa-heart fa-2x"></i><span class="mx-2">いいねした投稿</span>
                  <% end %>
                </a>
              </li>

              <!--フォロー関連情報のページに遷移-->
              <li class="nav-item">
                <a class="nav-link">
                  <%= link_to customer_index_path(current_customer.id), :style=>"text-decoration: none; color: #000;" do %>
                    <i class="fas fa-users fa-2x"></i><span class="mx-2">フォロー</span>
                  <% end %>
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link">
                  <%= link_to  new_like_path, :style=>"text-decoration: none; color: #000;" do %>
                    <i class="fas fa-star fa-2x"></i></i><span class="mx-2">趣味を投稿</span>
                  <% end %>
                </a>
              </li>

              <!--ゲストログイン時のヘッダー-->
              <% else %>

              <!--ホーム画面に遷移-->
              <li class="nav-item">
                <a class="nav-link active" aria-current="page">
                  <%= link_to root_path, :style=>"text-decoration: none; color: #000;" do %>
                    <i class="fas fa-home fa-2x"></i>ホーム
                  <% end %>
                </a>
              </li>

              <!--about画面に遷移-->
              <li class="nav-item">
                <a class="nav-link active" aria-current="page">

                  <%= link_to about_path, :style=>"text-decoration: none; color: #000;" do %>
                    <i class="fas fa-home fa-2x"></i>サイト説明
                  <% end %>
                </a>
              </li>

              <% end %>

            </ul>
          </div>
        </div>

        <div class="col-md-9">
          <div class="row">
          <%= yield %>
          </div>
        </div>

      </div>
    </div>

    <footer>
      <div>
        <p>
          <% if admin_signed_in? %>
            <p class="text-white">© 2023 ko-ta</p>
          <% elsif customer_signed_in? %>
            <p class="text-white">© 2023 ko-ta</p>
          <% else %>
            <%= link_to  new_admin_session_path, :style=>"text-decoration: none; color: #fff;" do%>© 2023 ko-ta<% end %>
          <% end %>
        </p>
      </div>
    </footer>
  </body>
</html>